# Generated by Django 5.1.15 on 2026-07-01 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=180)),
                ('cidade', models.CharField(max_length=80)),
                ('curso_turma', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=30, unique=True)),
                ('observacoes', models.TextField(blank=True)),
                ('login', models.CharField(max_length=50, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Leitor',
                'verbose_name_plural': 'Leitores',
                'ordering': ['nome'],
            },
        ),
    ]
